services:

    Markocupic\SacEventToolBundle\Controller\Download\DownloadController:
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@Markocupic\SacEventToolBundle\Pdf\PrintWorkshopsAsPdf'
            - '@Markocupic\SacEventToolBundle\Docx\ExportEvents2Docx'
            - '@monolog.logger.contao'

        public: true
