services:

    # MaintainBackendUser
    Markocupic\SacEventToolBundle\ContaoBackendMaintainance\MaintainBackendUser:
        public: true
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@Markocupic\SacEventToolBundle\User\BackendUser\MaintainBackendUserRights'
            - '@monolog.logger.contao'
