services:

    Markocupic\SacEventToolBundle\Controller\Api\EventApiController:
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@database_connection'
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        public: true
