services:

    Markocupic\SacEventToolBundle\Controller\Download\DownloadController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@Markocupic\SacEventToolBundle\Pdf\WorkshopBookletGenerator'
            - '@monolog.logger.contao'

        public: true
