services:

  markocupic.sac_event_tool_bundle.controller.content_element.user_portrait_controller:
    class: Markocupic\SacEventToolBundle\Controller\ContentElement\UserPortraitController
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    tags:
    - { name: contao.content_element, category: sac_event_tool_content_elements, type: user_portrait }
    - { name: container.service_subscriber }
    public: true

  markocupic.sac_event_tool_bundle.controller.content_element.cabanne_sac_detail_controller:
    class: Markocupic\SacEventToolBundle\Controller\ContentElement\CabanneSacDetailController
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    tags:
    - { name: contao.content_element, category: sac_event_tool_content_elements, type: cabanne_sac_detail }
    - { name: container.service_subscriber }
    public: true

  markocupic.sac_event_tool_bundle.controller.content_element.cabanne_sac_list_controller:
    class: Markocupic\SacEventToolBundle\Controller\ContentElement\CabanneSacListController
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    tags:
    - { name: contao.content_element, category: sac_event_tool_content_elements, type: cabanne_sac_list }
    - { name: container.service_subscriber }
    public: true

  markocupic.sac_event_tool_bundle.controller.content_element.user_portrait_list_controller:
    class: Markocupic\SacEventToolBundle\Controller\ContentElement\UserPortraitListController
    calls:
    - ['setContainer', ['@Psr\Container\ContainerInterface']]
    tags:
    - { name: contao.content_element, category: sac_event_tool_content_elements, type: user_portrait_list }
    - { name: container.service_subscriber }
    public: true
