services:

    Markocupic\SacEventToolBundle\Controller\FrontendModule\TourDifficultyListController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
            - { name: container.service_subscriber }
        public: true

    Markocupic\SacEventToolBundle\Controller\FrontendModule\CsvEventMemberExportController:
        arguments:
            - '@contao.framework'
            - '@database_connection'
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
        public: true

    Markocupic\SacEventToolBundle\Controller\FrontendModule\EventRegistrationCheckoutLinkController:
        arguments:
            - '@contao.framework'
            - '@contao.routing.scope_matcher'
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
            - { name: container.service_subscriber }
        public: true

    Markocupic\SacEventToolBundle\Controller\FrontendModule\EventRegistrationController:
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@security.helper'
            - '@event_dispatcher'
            - '@twig'
            - '@translator'
            - '%kernel.project_dir%'
            - '@monolog.logger.contao'
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
        public: true

    # Member dashboard module: show upcoming events
    Markocupic\SacEventToolBundle\Controller\FrontendModule\MemberDashboardUpcomingEventsController:
        arguments:
            - '@contao.framework'
            - '@security.helper'
            - '%sacevt.locale%'
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
        public: true

    # Member dashboard module: show past events
    Markocupic\SacEventToolBundle\Controller\FrontendModule\MemberDashboardPastEventsController:
        arguments:
            - '@Markocupic\CloudconvertBundle\Conversion\ConvertFile'
            - '%kernel.project_dir%'
            - '%sacevt.temp_dir%'
            - '%sacevt.event.template.course_confirmation%'
            - '%sacevt.event.course_confirmation_file_name_pattern%'
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
            - { name: container.service_subscriber }
        public: true

    # Member dashboard module: display the member profile
    Markocupic\SacEventToolBundle\Controller\FrontendModule\MemberDashboardProfileController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
            - { name: container.service_subscriber }
        public: true

    # Member dashboard module: display the forms for editing the member profile
    Markocupic\SacEventToolBundle\Controller\FrontendModule\MemberDashboardEditProfileController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
            - { name: container.service_subscriber }
        public: true

    # Member dashboard module: display the forms for editing the member profile
    Markocupic\SacEventToolBundle\Controller\FrontendModule\MemberDashboardAvatarController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        arguments:
            - '@request_stack'
            - '@contao.routing.scope_matcher'
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
            - { name: container.service_subscriber }
        public: true

    # Member dashboard module: display the form for deleting the member profile
    Markocupic\SacEventToolBundle\Controller\FrontendModule\MemberDashboardDeleteProfileController:
        arguments:
            - '@contao.framework'
            - '@security.helper'
            - '@Markocupic\SacEventToolBundle\User\FrontendUser\ClearFrontendUserData'
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
            - { name: container.service_subscriber }
        public: true

    # Member dashboard module: display the avatar and the avatar upload form
    Markocupic\SacEventToolBundle\Controller\FrontendModule\MemberDashboardAvatarUploadController:
        arguments:
            - '@contao.framework'
            - '@security.helper'
            - '@Markocupic\SacEventToolBundle\Image\RotateImage'
            - '%kernel.project_dir%'
            - '%sacevt.user.frontend.avatar_dir%'
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
        public: true

    # Event filter form module
    Markocupic\SacEventToolBundle\Controller\FrontendModule\EventFilterFormController:
        arguments:
            - '@contao.framework'
            - '@translator'
            - '%sacevt.locale%'
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
        public: true

    # Jahresprpgramm export module
    Markocupic\SacEventToolBundle\Controller\FrontendModule\JahresprogrammExportController:
        arguments:
            - '@contao.framework'
            - '@request_stack'
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
        public: true

    # Pilatus export module
    Markocupic\SacEventToolBundle\Controller\FrontendModule\PilatusExport2021Controller:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@contao.insert_tag.parser'
        public: true

    # Csv Export module: Export members and users as a csv spreadsheet
    Markocupic\SacEventToolBundle\Controller\FrontendModule\CsvExportController:
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@database_connection'
            - '@translator'
            - '@Markocupic\SacEventToolBundle\Download\BinaryFileDownload'
            - '%sacevt.temp_dir%'
            - '%kernel.project_dir%'
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
        public: true

    # Event Auflistungs Modul
    Markocupic\SacEventToolBundle\Controller\FrontendModule\EventListController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        tags:
            - { name: contao.frontend_module, category: sac_event_tool_frontend_modules }
            - { name: container.service_subscriber }
        public: true
