services:

    # Get the contao mode (TL_MODE)
    Markocupic\SacEventToolBundle\ContaoScope\ContaoScope:
        public: true
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@contao.routing.scope_matcher'

