services:

    Markocupic\SacEventToolBundle\Controller\Feed\UpcomingEventsController:
        arguments:
            - '@contao.framework'
            - '@Markocupic\RssFeedGeneratorBundle\Feed\FeedFactory'
            - '@database_connection'
            - '%kernel.project_dir%'
            - '%sacevt.locale%'
        public: true


