services:
    Markocupic\SacEventToolBundle\Controller\Ajax\MemberDashboardWriteEventArticleController:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@contao.csrf.token_manager'
            - '@request_stack'
            - '@security.helper'
            - '@translator'
            - '@Markocupic\SacEventToolBundle\Image\RotateImage'
            - '%kernel.project_dir%'
            - '%contao.csrf_token_name%'
        public: true

    Markocupic\SacEventToolBundle\Controller\Api\EventApiController:
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@database_connection'
        public: true
