services:

    # Contao Cron Controller
    Markocupic\SacEventToolBundle\Cron\Contao\DailyCron:
        public: true
        arguments:
            - '@contao.framework'

    # Contao Cron Controller
    Markocupic\SacEventToolBundle\Cron\Contao\HourlyCron:
        public: true
        arguments:
            - '@contao.framework'



