services:
    Markocupic\SacEventToolBundle\DataContainer\Util:
        arguments:
            - '@request_stack'

    Markocupic\SacEventToolBundle\DataContainer\User:
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@database_connection'
            - '@translator'
            - '@Contao\CoreBundle\Intl\Countries'
            - '@Markocupic\SacEventToolBundle\User\BackendUser\MaintainBackendUsersHomeDirectory'

    Markocupic\SacEventToolBundle\DataContainer\EventFilterForm:
        arguments:
            - '@database_connection'

    Markocupic\SacEventToolBundle\DataContainer\CalendarEventsInstructorInvoice:
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@database_connection'
            - '@Markocupic\SacEventToolBundle\DataContainer\Util'
            - '@translator'
            - '@security.helper'
            - '@Markocupic\SacEventToolBundle\DocxTemplator\EventRapport2Docx'
            - '%sacevt.event.template.tour_invoice%'
            - '%sacevt.event.template.tour_rapport%'
            - '%sacevt.event.tour_invoice_file_name_pattern%'
            - '%sacevt.event.tour_rapport_file_name_pattern%'

    Markocupic\SacEventToolBundle\DataContainer\Content:
        arguments:
            - '@database_connection'

    Markocupic\SacEventToolBundle\DataContainer\Calendar:
        arguments:
            - '@Markocupic\SacEventToolBundle\DataContainer\Util'

    Markocupic\SacEventToolBundle\DataContainer\CalendarContainer:
        arguments:
            - '@request_stack'
            - '@database_connection'
            - '@Markocupic\SacEventToolBundle\DataContainer\Util'
            - '@security.helper'

    Markocupic\SacEventToolBundle\DataContainer\EventReleaseLevelPolicy:
        arguments:
            - '@translator'

    Markocupic\SacEventToolBundle\DataContainer\EventReleaseLevelPolicyPackage:
        arguments:
            - '@security.helper'

    Markocupic\SacEventToolBundle\DataContainer\EventType: ~

    Markocupic\SacEventToolBundle\DataContainer\UserRole:
        arguments:
            - '@database_connection'
            - '@translator'

    Markocupic\SacEventToolBundle\DataContainer\Member:
        arguments:
            - '@translator'
            - '@Markocupic\SacEventToolBundle\User\FrontendUser\ClearFrontendUserData'

    Markocupic\SacEventToolBundle\DataContainer\Module: ~

    Markocupic\SacEventToolBundle\DataContainer\TourDifficulty: ~

    Markocupic\SacEventToolBundle\DataContainer\TourDifficultyCategory:
        arguments:
            - '@security.helper'



