services:

    Markocupic\SacEventToolBundle\DataContainer\User:
        arguments:
            - '@contao.framework'
            - '@request_stack'
            - '@database_connection'
            - '@security.helper'
            - '@translator'
            - '@Markocupic\SacEventToolBundle\User\BackendUser\MaintainBackendUsersHomeDirectory'
