services:
    # CorsListener Enable Cors requests
    Markocupic\SacEventToolBundle\EventListener\Cors\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }


    # CONTAO HOOKS:
    # Contao add custom regexp hook
    Markocupic\SacEventToolBundle\EventListener\Contao\AddCustomRegexpListener:
        public: true
        arguments:
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: contao.add_custom_regexp, method: onAddCustomRegexp }

    # Contao change event release level hook
    Markocupic\SacEventToolBundle\EventListener\Contao\ChangeEventReleaseLevelListener:
        public: true
        arguments:
            - "@contao.framework"
            - '@Markocupic\SacEventToolBundle\ContaoMode\ContaoMode'
        tags:
            - { name: kernel.event_listener, event: contao.change_event_release_level, method: onChangeEventReleaseLevel }

    # Contao publish event hook
    Markocupic\SacEventToolBundle\EventListener\Contao\PublishEventListener:
        public: true
        arguments:
            - "@contao.framework"
            - '@Markocupic\SacEventToolBundle\ContaoMode\ContaoMode'
        tags:
            - { name: kernel.event_listener, event: contao.publish_event, method: onPublishEvent }

    # Contao get page layout hook (purge script cache in debug mode only frontend)
    Markocupic\SacEventToolBundle\EventListener\Contao\GetPageLayoutListener:
        public: true
        class: Markocupic\SacEventToolBundle\EventListener\Contao\GetPageLayoutListener
        arguments:
            - "@contao.framework"
            - "@kernel"
            - '%kernel.project_dir%'
        tags:
            - { name: kernel.event_listener, event: contao.get_page_layout, method: purgeScriptCacheInDebugMode }

    # Contao get system messages hook (list untreated event subscriptions when logging in into the backend)
    Markocupic\SacEventToolBundle\EventListener\Contao\GetSystemMessagesListener:
        public: true
        arguments:
            - "@contao.framework"
            - '@Markocupic\SacEventToolBundle\ContaoMode\ContaoMode'

        tags:
            - { name: kernel.event_listener, event: get_system_messages_listener, method: listUntreatedEventSubscriptions }

    # Contao execute pre actions hook
    Markocupic\SacEventToolBundle\EventListener\Contao\ExecutePreActionsListener:
        public: true
        arguments:
            - "@contao.framework"
            - "@database_connection"
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: execute_pre_actions_listener, method: onExecutePreActions }

    # Contao import user hook (Allow users to login into the backend with their sacMemberId)
    Markocupic\SacEventToolBundle\EventListener\Contao\ImportUserListener:
        public: true
        arguments:
            - "@contao.framework"
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: import_user_listener, method: onImportUser }

    # Contao initialize system hook (Prepare the SAC Event Tool plugin environment)
    Markocupic\SacEventToolBundle\EventListener\Contao\InitializeSystemListener:
        public: true
        arguments:
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: initialize_system_listener, method: onInitializeSystem }

    # Contao parse template hook (Check if frontend login is allowed, if not replace the default error message and redirect to account activation page)
    Markocupic\SacEventToolBundle\EventListener\Contao\ParseTemplateListener:
        public: true
        arguments:
            - "@contao.framework"
            - '@request_stack'
            - '@contao.routing.scope_matcher'
        tags:
            - { name: kernel.event_listener, event: parse_template_listener, method: onParseTemplate }

    # Contao post login hook (Create backend user home directories if they does not exist & remove no more used directories)
    Markocupic\SacEventToolBundle\EventListener\Contao\PostLoginListener:
        public: true
        arguments:
            - '@contao.framework'
            - '@Markocupic\SacEventToolBundle\User\BackendUser\MaintainBackendUsersHomeDirectory'
        tags:
            - { name: kernel.event_listener, event: post_login_listener, method: onPostLogin }

    # Contao parse backend template hook (manipulate backend templates)
    Markocupic\SacEventToolBundle\EventListener\Contao\ParseBackendTemplateListener:
        public: true
        arguments:
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: parse_backend_template_listener, method: onParseBackendTemplate }

    # Contao replace insert tags hook (Use custom inserttags)
    Markocupic\SacEventToolBundle\EventListener\Contao\ReplaceInsertTagsListener:
        public: true
        arguments:
            - "@contao.framework"
        tags:
            - { name: kernel.event_listener, event: replace_insert_tags_listener, method: onReplaceInsertTags }

    Markocupic\SacEventToolBundle\EventListener\Contao\PreviewUrlCreateListener:
        arguments:
            - '@request_stack'
            - '@contao.framework'
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_create, method: onPreviewUrlCreate }

    Markocupic\SacEventToolBundle\EventListener\Contao\PreviewUrlConvertListener:
        arguments:
            - '@request_stack'
            - '@contao.framework'
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_convert, method: onPreviewUrlConvert }

    # END CONTAO HOOKS
