services:

  # Initialize System Hook
  markocupic_sac_event_tool.contao_hooks.initialize_system:
    public: true
    class: Markocupic\SacEventToolBundle\ContaoHooks\InitializeSystem
    arguments:
    - "@contao.framework"


  # Parse Backend Template
  markocupic_sac_event_tool.contao_hooks.parse_backend_template:
    public: true
    class: Markocupic\SacEventToolBundle\ContaoHooks\ParseBackendTemplate
    arguments:
    - "@contao.framework"


  # Execute Pre Actions
  markocupic_sac_event_tool.contao_hooks.execute_pre_actions:
    public: true
    class: Markocupic\SacEventToolBundle\ContaoHooks\ExecutePreActions
    arguments:
    - "@contao.framework"

  # Contao add custom regexp hook
  markocupic.sac_event_tool_bundle.event_listener.add_custom_regexp:
    public: true
    class: Markocupic\SacEventToolBundle\EventListener\AddCustomRegexpListener
    arguments:
    - "@contao.framework"
    tags:
    - { name: kernel.event_listener, event: contao.add_custom_regexp, method: onAddCustomRegexp }



