ajax_frontend:
    resource: "@MarkocupicSacEventToolBundle/Controller"
    type: annotation
    defaults:
        _scope: frontend
        _token_check: true

cronjob:
    resource: "@MarkocupicSacEventToolBundle/Controller"
    type: annotation