sac_event_tool_ajax_frontend:
    resource: "@MarkocupicSacEventToolBundle/Controller"
    type: annotation
    defaults:
        _scope: frontend
        _token_check: true

sac_event_tool_cronjob:
    resource: "@MarkocupicSacEventToolBundle/Controller"
    type: annotation