services:

    # Sync member database form Bern with contao core database tl_member
    Markocupic\SacEventToolBundle\SacMemberDatabase\SyncSacMemberDatabase:
        public: true
        arguments:
            - '@contao.framework'
            - '%sacevt.member_sync_credentials%'
            - '%sacevt.section_ids%'
            - '%kernel.project_dir%'
            - '@monolog.logger.contao'

    # Controller: sync database
    Markocupic\SacEventToolBundle\Controller\SacMemberDatabase\SyncMemberDatabase:
        public: true
        arguments:
            - '@contao.framework'
            - '@Markocupic\SacEventToolBundle\SacMemberDatabase\SyncSacMemberDatabase'
