services:

  # Sync member database form Bern with contao core database tl_member
  Markocupic\SacEventToolBundle\SacMemberDatabase\SyncSacMemberDatabase:
    public: true
    arguments:
    - '@contao.framework'
    - '%kernel.project_dir%'
    - '@monolog.logger.contao'

