services:

    # Sync member database form Bern with contao core database tl_member
    Markocupic\SacEventToolBundle\SacMemberDatabase\SyncSacMemberDatabase:
        public: true
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@security.encoder_factory'
            - '%sacevt.member_sync_credentials%'
            - '%kernel.project_dir%'
            - '%sacevt.locale%'
            - '@monolog.logger.contao'

    # Controller: sync database
    Markocupic\SacEventToolBundle\Controller\SacMemberDatabase\SyncMemberDatabase:
        public: true
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
        arguments:
            - '@contao.framework'
            - '@Markocupic\SacEventToolBundle\SacMemberDatabase\SyncSacMemberDatabase'
