services:
    markocupic.sac_event_tool_bundle.prepare_plugin_environment:
        class: Markocupic\SacEventToolBundle\PreparePluginEnvironment
        arguments:
            - "@contao.framework"

    markocupic.sac_event_tool_bundle.sync_sac_member_database:
        class: Markocupic\SacEventToolBundle\Services\SacMemberDatabase\SyncSacMemberDatabase
        arguments:
            - "@contao.framework"
            - "@database_connection"
            - "%kernel.project_dir%"
        public: true

