services:

    # For test purposes only
    Markocupic\SacEventToolBundle\Controller\TestController:
        public: true
        arguments:
            - '@database_connection'
            - '@contao.framework'
            - '@twig'
        tags:
            - { name: container.service_subscriber }
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]

    # Add a session bag
    Markocupic\SacEventToolBundle\Session\Attribute\ArrayAttributeBag:
        arguments:
            - '_markocupic_sac_event_tool_attributes'
        calls:
            - [ setName, [ 'markocupic_sac_event_tool_attributes' ] ]

    # Generate docx/pdf event memberlists from docx templates
    Markocupic\SacEventToolBundle\DocxTemplator\EventMemberList2Docx:
        public: true
        arguments:
            - '@contao.framework'
            - '@Markocupic\SacEventToolBundle\DocxTemplator\Helper\Event'
            - '@Markocupic\SacEventToolBundle\DocxTemplator\Helper\EventMember'
            - '@Markocupic\CloudconvertBundle\Conversion\ConvertFile'
            - '%sacevt.temp_dir%'
            - '%kernel.project_dir%'
            - '%sacevt.event.template.member_list%'
            - '%sacevt.event.member_list_file_name_pattern%'

    # Generate csv event registration list
    Markocupic\SacEventToolBundle\Csv\ExportEventRegistrationList:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '%sacevt.event.member_list_file_name_pattern%'

    # Generate docx/pdf event rapports and event invoices from docx templates
    Markocupic\SacEventToolBundle\DocxTemplator\EventRapport2Docx:
        public: true
        arguments:
            - '@contao.framework'
            - '@Markocupic\CloudconvertBundle\Conversion\ConvertFile'
            - '%kernel.project_dir%'
            - '%sacevt.temp_dir%'

    # Generate docx/pdf event rapports, event invoices and event memberlists from docx templates
    Markocupic\SacEventToolBundle\DocxTemplator\Helper\Event:
        public: true
        arguments:
            - '@contao.framework'
            - '%kernel.project_dir%'

    # Generate docx/pdf event rapports, event invoices and event memberlists from docx templates
    Markocupic\SacEventToolBundle\DocxTemplator\Helper\EventMember:
        public: true
        arguments:
            - '@contao.framework'
            - '%kernel.project_dir%'

    # Clear/Anonymize frontend user data f.ex if frontend user has been deleted
    Markocupic\SacEventToolBundle\User\FrontendUser\ClearFrontendUserData:
        public: true
        arguments:
            - '@contao.framework'
            - '%kernel.project_dir%'
            - '%sacevt.user.frontend.avatar_dir%'

    # Generate backend users home directory / remove old backend user home directories
    Markocupic\SacEventToolBundle\User\BackendUser\MaintainBackendUsersHomeDirectory:
        public: true
        arguments:
            - '@contao.framework'
            - '%kernel.project_dir%'
            - '%sacevt.user.backend.home_dir%'

    # Clear backend user properties
    Markocupic\SacEventToolBundle\User\BackendUser\MaintainBackendUserProperties:
        public: true
        arguments:
            - '@contao.framework'
            - '@database_connection'

    # Cron: Sync tl_member with tl_user
    Markocupic\SacEventToolBundle\User\BackendUser\SyncMemberWithUser:
        public: true
        arguments:
            - '@contao.framework'
            - '@monolog.logger.contao'

    # Rotate image
    Markocupic\SacEventToolBundle\Image\RotateImage:
        public: true
        arguments:
            - '@contao.framework'
            - '%kernel.project_dir%'

    # Generate worhshop booklet
    Markocupic\SacEventToolBundle\Pdf\WorkshopBookletGenerator:
        public: true
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@Markocupic\SacEventToolBundle\Download\BinaryFileDownload'
            - '%kernel.project_dir%'
            - '%sacevt.temp_dir%'
            - '%sacevt.event.course.booklet_filename_pattern%'

    # Export events as docx file
    Markocupic\SacEventToolBundle\Docx\ExportEvents2Docx:
        public: true
        arguments:
            - '@contao.framework'
            - '@Markocupic\SacEventToolBundle\Download\BinaryFileDownload'
            - '%kernel.project_dir%'

    # Send ical to the browser
    Markocupic\SacEventToolBundle\Ical\SendEventIcal:
        public: true
        arguments:
            - '@contao.framework'
            - '@Contao\CoreBundle\InsertTag\InsertTagParser'

    # Send file to the browser
    Markocupic\SacEventToolBundle\Download\BinaryFileDownload:
        public: true

