services:
  markocupic.sac_event_tool_bundle.prepare_plugin_environment:
    public: true
    class: Markocupic\SacEventToolBundle\PreparePluginEnvironment
    arguments:
    - '@contao.framework'

  markocupic.sac_event_tool_bundle.sync_sac_member_database:
    public: true
    class: Markocupic\SacEventToolBundle\Services\SacMemberDatabase\SyncSacMemberDatabase
    arguments:
    - '@contao.framework'
    - '@database_connection'
    - '%kernel.project_dir%'

  markocupic.sac_event_tool_bundle.services.cors.cors_listener:
    class:  Markocupic\SacEventToolBundle\Services\Cors\CorsListener
    tags:
    - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

  markocupic.sac_event_tool_bundle.controller.frontend_module.tour_difficulty_list_controller:
    class: Markocupic\SacEventToolBundle\Controller\FrontendModule\TourDifficultyListController
    arguments:
    - '@contao.framework'
    tags:
    - { name: contao.frontend_module, category: sac_event_tool_fe_modules }
    public: true

  markocupic.sac_event_tool_bundle.controller.frontend_module.csv_event_member_export:
    class: Markocupic\SacEventToolBundle\Controller\FrontendModule\CsvEventMemberExportController
    arguments:
    - '@contao.framework'
    - '@database_connection'
    - '@request_stack'
    tags:
    - { name: contao.frontend_module, category: sac_event_tool_fe_modules }
    public: true

  markocupic.sac_event_tool_bundle.controller.frontend_module.event_registration_form:
    class: Markocupic\SacEventToolBundle\Controller\FrontendModule\EventRegistrationFormController
    arguments:
    - '@contao.framework'
    - '@database_connection'
    - '%kernel.project_dir%'
    - '@security.helper'
    - '@request_stack'
    - '@contao.routing.scope_matcher'
    tags:
    - { name: contao.frontend_module, category: sac_event_tool_fe_modules }
    public: true


