services:

  # Contao Backend Module "Maintenance": Delete no more used event stories media directories
  Markocupic\SacEventToolBundle\ContaoBackendMaintenance\MaintainModuleEventStory:
    public: true
    arguments:
    - '@contao.framework'
    - '%kernel.project_dir%'

  # Generate docx/pdf event memberlists from docx templates
  Markocupic\SacEventToolBundle\DocxTemplater\EventMemberList2Docx:
    public: true
    arguments:
    - '@contao.framework'
    - '%kernel.project_dir%'

  # Generate docx/pdf event rapports and event invoices from docx templates
  Markocupic\SacEventToolBundle\DocxTemplater\EventRapport2Docx:
    public: true
    arguments:
    - '@contao.framework'
    - '%kernel.project_dir%'

  # Generate docx/pdf event rapports, event invoices and event memberlists from docx templates
  Markocupic\SacEventToolBundle\DocxTemplater\Helper\Event:
    public: true
    arguments:
    - '@contao.framework'
    - '%kernel.project_dir%'

  # Generate docx/pdf event rapports, event invoices and event memberlists from docx templates
  Markocupic\SacEventToolBundle\DocxTemplater\Helper\EventMember:
    public: true
    arguments:
    - '@contao.framework'
    - '%kernel.project_dir%'

  # Clear/Anonymize frontend user data f.ex if frontend user has been deleted
  Markocupic\SacEventToolBundle\User\FrontendUser\ClearFrontendUserData:
    public: true
    arguments:
    - '@contao.framework'
    - '%kernel.project_dir%'

  # Generate backend users home directory / remove old backend user home directories
  Markocupic\SacEventToolBundle\User\BackendUser\MaintainBackendUsersHomeDirectory:
    public: true
    arguments:
    - '@contao.framework'
    - '%kernel.project_dir%'

  # Cron: Replace default password and send email to user with new pw
  Markocupic\SacEventToolBundle\User\BackendUser\ReplaceDefaultPassword:
    public: true
    arguments:
    - '@contao.framework'

  # Rotate image
  Markocupic\SacEventToolBundle\Image\RotateImage:
    public: true
    arguments:
    - '@contao.framework'
    - '%kernel.project_dir%'

  # Generate worhshop booklet
  Markocupic\SacEventToolBundle\Pdf\PrintWorkshopsAsPdf:
    public: true
    arguments:
    - '@contao.framework'

  # Send ical
  Markocupic\SacEventToolBundle\Ical\SendEventIcal:
    public: true




