services:

    # Twig extensions
    Markocupic\SacEventToolBundle\Twig\TwigAssetManager:
        tags:
            - { name: twig.extension }

    Markocupic\SacEventToolBundle\Twig\TwigAvatarManager:
        arguments:
            - '@Markocupic\SacEventToolBundle\Avatar\Avatar'
        tags:
            - { name: twig.extension }

    Markocupic\SacEventToolBundle\Twig\TwigLoggedInFrontendUserManager:
        arguments:
            - '@contao.framework'
            - '@security.helper'
        tags:
            - { name: twig.extension }
