services:
    # CorsListener Enable Cors requests
    Markocupic\SacEventToolBundle\EventListener\Cors\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }


    # CONTAO HOOKS:
    # Contao add custom regexp hook
    Markocupic\SacEventToolBundle\EventListener\Contao\SacEvtOnGenerateEventDashboardListener:
        public: true
        arguments:
            - '@contao.framework'
            - '@security.helper'
        tags:
            - { name: contao.hook, hook: sacEvtOnGenerateEventDashboard, method: onGenerateEventDashboardListener, priority: 100 }

    # Contao add custom regexp hook
    Markocupic\SacEventToolBundle\EventListener\Contao\AddCustomRegexpListener:
        public: true
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: addCustomRegexp, method: onAddCustomRegexp }

    # Contao change event release level hook
    Markocupic\SacEventToolBundle\EventListener\Contao\ChangeEventReleaseLevelListener:
        public: true
        arguments:
            - '@contao.framework'
            - '@Markocupic\SacEventToolBundle\ContaoScope\ContaoScope'
        tags:
            - { name: contao.hook, hook: changeEventReleaseLevel, method: onChangeEventReleaseLevel }

    # Contao publish event hook
    Markocupic\SacEventToolBundle\EventListener\Contao\PublishEventListener:
        public: true
        arguments:
            - '@contao.framework'
            - '@Markocupic\SacEventToolBundle\ContaoScope\ContaoScope'
        tags:
            - { name: contao.hook, hook: publishEvent, method: onPublishEvent, priority: 0 }

    # Contao get page layout hook (purge script cache in debug mode only frontend)
    Markocupic\SacEventToolBundle\EventListener\Contao\GetPageLayoutListener:
        public: true
        class: Markocupic\SacEventToolBundle\EventListener\Contao\GetPageLayoutListener
        arguments:
            - '@contao.framework'
            - '@kernel'
            - '%kernel.project_dir%'
        tags:
            - { name: contao.hook, hook: getPageLayout, method: purgeScriptCacheInDebugMode, priority: 0 }

    # Contao get system messages hook (list untreated event subscriptions when logging in into the backend)
    Markocupic\SacEventToolBundle\EventListener\Contao\GetSystemMessagesListener:
        public: true
        arguments:
            - '@contao.framework'
            - '@Markocupic\SacEventToolBundle\ContaoScope\ContaoScope'
        tags:
            - { name: contao.hook, hook: getSystemMessages, method: listUntreatedEventSubscriptions }

    # Contao execute pre actions hook
    Markocupic\SacEventToolBundle\EventListener\Contao\ExecutePreActionsListener:
        public: true
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: executePreActions, method: onExecutePreActions }

    # Contao import user hook (Allow users to login into the backend with their sacMemberId)
    Markocupic\SacEventToolBundle\EventListener\Contao\ImportUserListener:
        public: true
        arguments:
            - '@contao.framework'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: importUser, method: onImportUser }

    # Contao post login hook (Create backend user home directories if they do not exist & remove no more used directories)
    Markocupic\SacEventToolBundle\EventListener\Contao\PostLoginListener:
        public: true
        arguments:
            - '@contao.framework'
            - '@Markocupic\SacEventToolBundle\User\BackendUser\MaintainBackendUsersHomeDirectory'
        tags:
            - { name: contao.hook, hook: postLogin, method: onPostLogin }

    # Contao parse backend template hook (manipulate backend templates)
    Markocupic\SacEventToolBundle\EventListener\Contao\ParseBackendTemplateListener:
        public: true
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: parseBackendTemplate, method: onParseBackendTemplate }

    # Contao replace insert tags hook (Use custom inserttags)
    Markocupic\SacEventToolBundle\EventListener\Contao\ReplaceInsertTagsListener:
        public: true
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: replaceInsertTags, method: onReplaceInsertTags }

    Markocupic\SacEventToolBundle\EventListener\Contao\PreviewUrlCreateListener:
        arguments:
            - '@request_stack'
            - '@contao.framework'
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_create, method: onPreviewUrlCreate }

    Markocupic\SacEventToolBundle\EventListener\Contao\PreviewUrlConvertListener:
        arguments:
            - '@request_stack'
            - '@contao.framework'
        tags:
            - { name: kernel.event_listener, event: contao.preview_url_convert, method: onPreviewUrlConvert }

    # END CONTAO HOOKS
