'ca. 1 h':
    dateRows: 1
'ca. 2 h':
    dateRows: 1
'ca. 3 h':
    dateRows: 1
'ca. 4 h':
    dateRows: 1
'ca. 5 h':
    dateRows: 1
'ca. 6 h':
    dateRows: 1
'ca. 7 h':
    dateRows: 1
'ca. 8 h':
    dateRows: 1
'ca. 9 h':
    dateRows: 1
'1/2 Tag':
    dateRows: 1
'1 Tag':
    dateRows: 1
'1 1/2 Tage':
    dateRows: 2
'2 Tage':
    dateRows: 2
'2 1/2 Tage':
    dateRows: 3
'3 Tage':
    dateRows: 3
'3 1/2 Tage':
    dateRows: 4
'4 Tage':
    dateRows: 4
'4 1/2 Tage':
    dateRows: 5
'5 Tage':
    dateRows: 5
'5 1/2 Tage':
    dateRows: 6
'6 Tage':
    dateRows: 6
'6 1/2 Tage':
    dateRows: 7
'7 Tage':
    dateRows: 7
'7 1/2 Tage':
    dateRows: 8
'8 Tage':
    dateRows: 8
'8 1/2 Tage':
    dateRows: 9
'9 Tage':
    dateRows: 9
'9 1/2 Tage':
    dateRows: 10
'10 Tage':
    dateRows: 10
'10 1/2 Tage':
    dateRows: 11
'11 Tage':
    dateRows: 11
'11 1/2 Tage':
    dateRows: 12
'12 Tage':
    dateRows: 12
'12 1/2 Tage':
    dateRows: 13
'13 Tage':
    dateRows: 13
'13 1/2 Tage':
    dateRows: 14
'14 Tage':
    dateRows: 14
'1 Vormittag':
    dateRows: 1
'2 Vormittage':
    dateRows: 2
'3 Vormittage':
    dateRows: 3
'4 Vormittage':
    dateRows: 4
'5 Vormittage':
    dateRows: 5
'6 Vormittage':
    dateRows: 6
'7 Vormittage':
    dateRows: 7
'1 Abend':
    dateRows: 1
'2 Abende':
    dateRows: 2
'3 Abende':
    dateRows: 3
'4 Abende':
    dateRows: 4
'5 Abende':
    dateRows: 5
'6 Abende':
    dateRows: 6
'7 Abende':
    dateRows: 7
'1 Abend und 1 Tag':
    dateRows: 2
